# Generated by Django 2.2.6 on 2019-10-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denunciaEnv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
